sudo: false
language: python
cache: pip
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
before_script: "pip install -r dev-requirements.txt"
install: "pip install -r requirements.txt"
script:
  - "flake8 vatsim_status/ tests/"
  - "python setup.py test"
